language: python

python:
    - 2.7

install:
    - pip install -U pip
    - pip install -U coverage coveralls
    - python setup.py install

script:
    - coverage run --source nvd3 -m unittest test_nvd3

after_success:
    - coveralls
